### ISSUE TITLE
Invalid encoding of sqs messages

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_registry2#105]
**Currently all modules are failing to publish - 5 are currently in the queue waiting to be published.**

SQS messages are not correctly encoded. `{"buildID":"5f4e2efc003bedbe00f27b79"}` turns into `%7B%22buildID%22%3A%225f4e2efc003bedbe00f27b79%22%7D` . This is an upstream issue with `https://deno.land/x/sqs@0.3.1`. I will be fixing this issue upstream shortly.

**Comment by wperron** [comment]
Possibly linked to #88 ?

**Comment by lucacasonato** [comment]
No linked to my update of https://deno.land/x/sqs@0.3.1 in #100 / #103

**Comment by lucacasonato** [comment]
Published https://deno.land/x/sqs@0.3.2 to fix this issue - now opening PR to update here.
