### ISSUE TITLE
Support for Multi Registry Module Publishing

### ISSUE THREAD

**Issue by michael-spengler** [denoland/deno_registry2#128]
Hi Ryan, William and Luca.

Could you think of a simple and sustainable option on how module developers could choose additional module registries during the webhook / release based publishing process? 

I think many of us want to publish many of their modules e.g. on https://deno.land/ AND on https://nest.land/

Both mechanisms are super straight forward from my perspective. At the same I'd find it even cooler if deno.land offered an option to "register registries" from which the module publisher could choose where to publish the module **additionally** to deno.land. 
The process behind your webhook could imo call the corresponding APIs of the other - chosen - registries.

This could be an additional incentive for module publishers to use deno.land as primary registry which I believe is great for many consumers who can with that have a promising single point of entry where to start their search for specific features / deno modules.

Kind regards
Michael

**Comment by wperron** [comment]
I can't speak for Luca or Ryan, but in my opinion this is something that should be handled in CI and not by the registry. The way I see it, the burden on the module authors to publish to different registries is much less than the burden on the deno.land registry to support this feature for every module authors and all deno registries.

I also feel like it would nudge people towards using the same publishing strategy in different registries, which isn't strictly necessary; you might want to publish only tagged versions to deno.land and nightly builds to nest.land for example, and that choice should be a conscious one by the module author.

**Comment by michael-spengler** [comment]
@wperron Thank you for the info. I think I understand your points. 

Regarding freedom & diversity:
As the Multi Registry Module Publishing would be optional for the module publishers they would imo still have the freedom to do what you described

Regarding the burden comparison:
In case of millions of valuable Deno modules I can imagine that the proposed feature would optionally save developers a lot of time 

Perhaps there will be a main Deno module marketplace one day which might connect to several Deno module registries - serving as a single point of entry - esp. for people searching for a specific feature / module.

**Comment by michael-spengler** [comment]
Thesis: 
If this central marketplace will be 
1. provided as a permaapp - e.g. via http://arweaveapps.com/ 
2. organized / moderated by a decentral autonomous organization (DAO) 
3. incentivized by a corresponding profit sharing token (PSC) 

... this might be a good idea.

**Comment by michael-spengler** [comment]
In some sense this could also lead to a more representative evaluation of Deno modules than e.g. star based or download based evaluation.

--> This might lead to an increased efficiency for finding the perfect module for a specific feature. I'd appreciate such a marketplace from consumer's- and from contributor's perspective.

**Comment by michael-spengler** [comment]
just decided with @wperron to close this issue --> clarifying implementation details for "standalone solution" - see previous comment -  in nest.land discord: https://discord.gg/CJYvc2N
