### ISSUE TITLE
Only show modules with published versions in the Recent Modules

### ISSUE THREAD

**Issue by wperron** [denoland/deno_registry2#142]
This was brought up by someone on the Discord channel, the "recently added" section currently shows any newly registered module, even if they have no published versions. It would be nice to only show modules that have at least one published version.

**Comment by wperron** [comment]
Just took a quick look at the code, we would have to join the `builds` and `modules` collections like in #143

**Comment by crowlKats** [comment]
Closing as we dont have recent modules anymore
