### ISSUE TITLE
Stars in the stats section should be displayed in the "Recently Updated" list as well

### ISSUE THREAD

**Issue by notfilippo** [denoland/deno_registry2#143]
The current Stats section (https://deno.land/x#stats) displays stars in the "New modules" module list. Modules in that list, being new, have 0 to 2 stars maximum each. I would make more sense to display star count in the "Recently Updated" list where modules have a higher star count.

**Comment by lucacasonato** [comment]
This is possible, but we would have to join the `builds` and `modules` table, making this a more expensive operation. Relative cost would only be 2n if current is n. Probably fine

**Comment by crowlKats** [comment]
Closing as we dont display stars anymore
