### ISSUE TITLE
Cache-Control settings are too long

### ISSUE THREAD

**Issue by wperron** [denoland/deno_registry2#147]
Looking at the network console in the browser, it seems the `versions.json` has a max-age of 14400 and `meta.json` has a max-age of 31536000.

This is unexpected as both these files are uploaded to s3 with different values for the max-age header. This is likely what's causing the issues of "no versions uploaded for this modules" or versions not updating on the website that pretty much every user has faced at some point.

**Comment by wperron** [comment]
@lucacasonato did you ever manage to investigate the issue? I can jump on that one and try it out on my staging environment; we keep getting questions in the Discord about this issue, would be nice to solve it.

**Comment by lucacasonato** [comment]
This should be fixed now.
