### ISSUE TITLE
Can't rename a GH repository tied to a module

### ISSUE THREAD

**Issue by hazae41** [denoland/deno_registry2#151]
1. Link a GH repository to a module
2. Rename the GH repository
3. Release a new version
4. The webhook fails with `module name is registered to a different repository`

`{"success":false,"error":"module name is registered to a different repository"}`

We should be able to change the registered GH repostitory of a module

**Comment by lucacasonato** [comment]
Changing the module is currently a manual process. What module do you want to change the repository for? I can manually transfer it.

**Comment by lucacasonato** [comment]
This should now be working. The system can now gracefully handle repo renames and organization transfers.
