### ISSUE TITLE
Got error when new version is published

### ISSUE THREAD

**Issue by Bunlong** [denoland/deno_registry2#157]
Hi --

I got error as following when I published new version. Please kindly check. Thanks!

Repositories
* [is-up](https://github.com/DenoOrg/is-up)
* [json](https://github.com/DenoOrg/json)
* [ip-address](https://github.com/DenoOrg/ip-address)
* [is-online](https://github.com/DenoOrg/is-online)
* [public-ip](https://github.com/deno-public-ip/public-ip)

![Screenshot from 2020-10-12 23-41-17](https://user-images.githubusercontent.com/1308397/95770973-7205ed80-0ce4-11eb-9837-2db689515262.png)

**Comment by ry** [comment]
You have been banned for squatting module names. Email me if you want to work it out.
