### ISSUE TITLE
CF worker: default to a list of the objects under the current prefix

### ISSUE THREAD

**Issue by wperron** [denoland/deno_registry2#181]
Right now cdn.deno.land returns a 403 on any URL that isn't an existing object, I'd like to add a default behavior that returns a list of the objects under under the directory in the path (either json or html based on the Accept header)

use case I have in mind for this is to make it easier to crawl the contents of the registries, especially by crawlers. Ultimately I'd like to build a crawler to build and maintain a graph of a all the dependencies between modules

**Comment by lucacasonato** [comment]
I don't really want to add this. I would rather people just use the deps_v2.json file (eg https://cdn.deno.land/std/versions/0.70.0/meta/deps_v2.json), or the directory listing (https://cdn.deno.land/std/versions/0.70.0/meta/meta.json).

**Comment by wperron** [comment]
That's a good a point I forgot about those. In fact probably very few people know about them, maybe we should document them better or add a sitemap or something.
