### ISSUE TITLE
500 Internal Server Error when trying to publish aws_sdk

### ISSUE THREAD

**Issue by christophgysin** [denoland/deno_registry2#182]
I have requested a quota increase for aws_sdk because we were hitting the 20Mb limit. The limit should have now been raised to 200Mb, but I'm getting HTTP 500 Internal Server Error for:

`X-GitHub-Delivery: fee42430-2bc8-11eb-9a46-6b506884fe9f`

Response:
```
HTTP 500 Internal Server Error
Apigw-Requestid: WWKppgSEoAMEPOA=
Content-Length: 35
Content-Type: text/plain; charset=utf-8
Date: Sat, 21 Nov 2020 07:14:06 GMT

{"message":"Internal Server Error"}
```

**Comment by lucacasonato** [comment]
Can you try publish v0.5.0 again? Should now be resolved.

**Comment by christophgysin** [comment]
Seems to work again, thanks!
