### ISSUE TITLE
Bug Report: No uploaded versions

### ISSUE THREAD

**Issue by hyurl** [denoland/deno_registry2#186]
The package name is [function_intercept](https://deno.land/x/function_intercept), after following the instruction, I create a tag `v1.1.0` and push it to GitHub, `deno.lang/x` do update and display it in the Stats section, however, when I click the link, it reports the following error:

```
No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed.
```

First I thought it might be a network problem, so I tried to increase the version number and re-push the tag, but it didn't work as well.

**Comment by bartlomieju** [comment]
I can see version `1.1.0` and `1.1.1`. Try hard refreshing the page, it might be cached in your browser.

**Comment by hyurl** [comment]
That actually works, strange behavior though.

**Comment by git136975643** [comment]
我也报这个错。刷新多次还是这个错。github已经设置网络钩子和tag版本。
GET https://cdn.deno.land/import_test/meta/versions.json 403
