### ISSUE TITLE
Pushing to `xdg` (with a duplicate named `xdg_portable`) has an "Internal Server Error"

### ISSUE THREAD

**Issue by rivy** [denoland/deno_registry2#204]
After pushing some early tests to <https://deno.land/x/xdg>, I recently had to reset the GitHub webhook of my repository and then inadvertently pushed a version of `xdg` to <https://deno.land/x/xdg_portable> (instead of the original <https://deno.land/x/xdg>).

After fixing the webhook, I see in the ["Recently updated"](https://deno.land/x) list that "xdg@v9.0.0" was received but the webhook reports an error:

```text
Header
Apigw-Requestid: avzNGiNaoAMEJlg=
Content-Length: 35
Content-Type: application/json
Date: Sun, 14 Feb 2021 18:01:43 GMT
Body
{"message":"Internal Server Error"}
```

and the module is not accessible at <https://deno.land/x/xdg@v9.0.0>. I expect it's because of the duplication, but I have no way to investigate the problem.

So, I'm unsure how to proceed.

<https://deno.land/x/xdg_portable> could be deleted or redirected to <https://deno.land/x/xdg> (if either are possible) or I can push to both to minimize confusion (if that's possible).

Thoughts on how to resolve?

**Comment by lucacasonato** [comment]
It seems that re-triggering a failed upload is not working correctly. I have manually deleted the previous build for xdg@v9.0.0. Can you try redeliver the webhook?

cc @wperron: in prod we have a index on the table that forces all builds for a module + version combo to be unique. To support re-triggering failed uploads, we need to delete the old build before triggering a new one.

**Comment by wperron** [comment]
@lucacasonato I think we can just remove the index to be honest, the publishing process should be resilient enough to work without it. Is there another feature that needs it?

I can take a look tomorrow, in the meantime I imagine you can take care of manually fixing the data to unblock @rivy ?

**Comment by lucacasonato** [comment]
Yup - manually fixed for now. I guess I can get rid of the index.

**Comment by rivy** [comment]
Thanks folks... since I pushed the one version to 'xdg_portable', should I keep pushing to it simultaneously (two webhooks) with 'xdg'?

**Comment by rivy** [comment]
@lucacasonato , the redelivery completed successfully. Thanks.

**Comment by rivy** [comment]
Jusy FYI, I've continued to push to both 'xdg' and 'xdg_portable' (without incident). If that's not acceptable, 'xdg_portable' could be deleted.

Anyway, thanks for fixing the roadblock for me.

**Comment by lucacasonato** [comment]
We don't delete modules. The registry is immutable
