### ISSUE TITLE
Discuss wiz_logger situation

### ISSUE THREAD

**Issue by sno2** [denoland/deno_registry2#207]
Hello, I understand that you include a notice on the [third party registry page](https://deno.land/x), but can you please remove [wiz_logger](https://deno.land/x/wiz_logger)?  I had misinterpreted how the subdirectory feature for modules worked and thought that it would still include my other code hidden in the backend but have pretty routes without the other folders/code.  It only has one version (v0.0.1-alpha3) which was committed an hour ago.  No one is even able to use the module anyways because it does not [include the other files that are in the GitHub repository](https://deno.land/x/wiz_logger@v0.0.1-alpha3/mod.ts#L1-L3) and it cannot resolve the files.  Thanks

**Comment by lucacasonato** [comment]
Thanks for reaching out, but we do not have an easy way to remove published modules. You can do a new release after removing the subdirectory parameter.

**Comment by sno2** [comment]
Ok, thanks.  Is there a way to transfer the module from looking at one repository to another?

**Comment by lucacasonato** [comment]
Yes, DM me on Discord: https://discord.gg/deno

**Comment by sno2** [comment]
Ok, thanks.

**Comment by sno2** [comment]
Lucas helped me move the source repo to fix the issue.
