### ISSUE TITLE
Folder size in directory listings falsely count other folders with same prefix

### ISSUE THREAD

**Issue by danopia** [denoland/deno_registry2#208]
For example here: https://deno.land/x/kubernetes_apis@v0.3.0/cert-manager

All 4 folders named `cert-manager.io@...` are the same rough size. However `cert-manager.io@v1` is counted as 4x its actual size, presumably because the files in `cert-manager.io@v1beta2` etc are all being counted against `cert-manager.io@v1`.

**Comment by wperron** [comment]
Nice catch! I'll look into it soon but from what I remember from the size counter this entirely possible

**Comment by wperron** [comment]
@danopia the issue's fixed, the calculation should be ok in the next versions
