### ISSUE TITLE
https://deno.land/x/chroma doesn't show up

### ISSUE THREAD

**Issue by NaridaL** [denoland/deno_registry2#213]
Hi, I tried to add https://github.com/NaridaL/chroma.ts to deno.land/x, but it's not showing up: https://deno.land/x/chroma (I deleted the last tag and readded it to trigger the webhook but no luck) 

Comparing with other repos, I probably shouldn't have specified "src/" as a subdirectory. Can I change that?

**Comment by wperron** [comment]
@NaridaL Sorry about the delay. There could be a couple of reasons no versions show up on the registry: Do you have any errors in your repository's webhook executions? If not, did you add your repo to deno.land/x before or adding the v1.0.10 tag?

**Comment by NaridaL** [comment]
I readded the tag now. The webhook gets a 500:

```
Headers

Apigw-Requestid: cIoaoiueIAMEPQA=
Content-Length: 35
Content-Type: application/json
Date: Sat, 13 Mar 2021 16:52:46 GMT

Body

{"message":"Internal Server Error"}

```

**Comment by wperron** [comment]
@NaridaL sorry about that, looks like we have a pesky bug there, can you redeliver the webhook again?

**Comment by NaridaL** [comment]
OK I redelivered it. I realized the subdir is part of the webhook URL. Should I try it without?

**Comment by wperron** [comment]
if it worked, then the version is published, so redelivering will fail because of that -- you'll have to remove the subdir and push a new version for it to take effect

**Comment by NaridaL** [comment]
OK, looks like the bug is fixed. Can we improve the description for the subdirectory?

Optional. A subdirectory in your repository that the module to be published is located in. In general, this is only required if the subdirectory is a logical, separately versioned module; not just the "src" directory.

**Comment by wperron** [comment]
Great, thanks for the follow-up :+1: Feel free to open a PR on the website repo if you want -- though there's really no such thing as "separately versioned" on deno.land/x. if you have multiple modules on different subdirs in the same repo, they will all get versioned along your git tags.
