### ISSUE TITLE
Errors when trying to publish: "Failed to clone git repository"

### ISSUE THREAD

**Issue by christophgysin** [denoland/deno_registry2#217]
I published v3.9.0.0 of aws_sdk:

https://deno.land/status/605ee67a00d42f4b00235928

Status: Error: Failed to clone git repository https://github.com/christophgysin/aws-sdk-js-v3 at tag v3.9.0.0

Despite the error, it seems that something was published at: https://deno.land/x/aws_sdk@v3.9.0.0, but "go to latest" still takes me to v3.8.1.0.

Possibly related to #209?

**Comment by wperron** [comment]
Looks like the repo weighs around 477.8Mb with a depth of 1 at the tag `v3.9.0.0`, considering that the limits for the `/tmp` folder on Lambda is 512Mb that doesn't leave a whole lotta room -- you're riding just at the limit (when accounting for the overhead of our own code etc). I'll see if there isn't something we can do at the platform level to avoid those limits but I'm not sure we'll be able to do much without moving off of Lambda (which isn't planned any time soon). In the meantime, if you ever get that error again you always try to redeliver the Webhook in github -- if the build wasn't successful it'll accept the tag even though it was already pushed.

As for the "latest" version, I agree that's not optimal; We already have two issues on that subject (see #214 and #196) so I'm gonna close in favor of those two issues.

**Comment by christophgysin** [comment]
@wperron Thanks for looking into it. You could increase temporary storage space by mounting EFS to lambda. But I can also see If I could automate pruning everything except the `deno/` subfolder before tagging a release, to cause less work for your backend tasks.

**Comment by christophgysin** [comment]
@wperron Could we please reopen this? I did some experiment with git clone filters and sparse checkout, and it's possible to clone the deno subfolder of aws_sdk with only 206Mb of disk space:
```
$ git clone --depth=1 --filter=blob:none --sparse https://github.com/christophgysin/aws-sdk-js-v3.git
$ cd aws-sdk-js-v3
$ git sparse-checkout set /deno
$ du -sh .
206M	.
```
I'm happy to create a PR to implement this.

**Comment by wperron** [comment]
sparse checkout sounds interesting, how would it work for repositories without a subdir parameter?

**Comment by christophgysin** [comment]
It won't change the disk usage if no subdir is specified since you already use depth=1. So you can either conditionally do the above if a subdir is specified, or do a sparse checkout of `${subdir}/*` (If subdir is the empty string `/*`will checkout everything as usual).

**Comment by christophgysin** [comment]
Ah, also this needs support from the remote repo, so if someone is running an ancient version of git this won't work. Maybe whitelist domains known to support it? Github does support it, and I can happily check a bunch of other popular domains.

**Comment by wperron** [comment]
So far and for the foreseeable future we only support GitHub anyway, so that's a non-issue.

> If subdir is the empty string /*will checkout everything as usual

Yes that's what I was wondering. Good, if we can use it without any impact on existing repos then great :+1:
