### ISSUE TITLE
Ignore-file when publishing new packages

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno_registry2#220]
I want to ignore some files inside the specified directory that I publish because they have nothing to do with Deno. They cause no harm as the code does in no way refer to them, but they are cluttering the overview and they are useless to cache on your side.

I'm building for Deno, Node, and the web all from the same code base. The other files are required for Node. I can specify Deno-specific files for exclusion from npm, however, I cannot exclude Node-specific files from `deno.land/x`.

Ideally, I'd like to have something like `.denolandignore`.

**Comment by kt3k** [comment]
From my experience with npm, I prefer include-list (`files` prop in package.json) to exclude-list (`.npmignore`) because include-list is easier to maintain. exclude-list often contains very random items and it's easy to forget to add items when necessary.

**Comment by KnorpelSenf** [comment]
> I prefer include-list

Works for me, too :+1:

**Comment by wperron** [comment]
I want to keep /x as simple and easy to use as possible, so it's a -1 from me. /x might not be the best fit for everyone and that's fine; that's the beautiful thing about the runtime being explicitly decentralized, you're not forced to use a specific module registry.

**Comment by KnorpelSenf** [comment]
What about permitting several entries when setting up the webhook? I could then specify the files and directories there, instead of having a configuration file. As you're resolving the subpath in the directory anyway, this should not be too much work, correct?

**Comment by wperron** [comment]
> What about permitting several entries when setting up the webhook? I could then specify the files and directories there, instead of having a configuration file. As you're resolving the subpath in the directory anyway, this should not be too much work, correct?

There's already a `subdir` parameter for the webhook that you can use like `?subdir=src/deno/` for example

**Comment by KnorpelSenf** [comment]
That's what I'm referring to. Specifying multiple of those subdirs could be used to replace a config file. It's another (and hopefully simpler) way to solve the same problem.

**Comment by wperron** [comment]
I'm not too keen on having configuration live in the webhook URL, it seems too brittle and hard to discover/remember to me. Seems to me like [nest.land](https://docs.nest.land/eggs/configuration) would suit your needs better than deno.land/x
