### ISSUE TITLE
how to nicely re-publish a project & case of pako

### ISSUE THREAD

**Issue by Akuukis** [denoland/deno_registry2#221]
### Situation

I published a module named [`pako`](https://deno.land/x/pako) earlier today because I'm trying out Deno and it was in my dependencies.

To do so, I created a [proxy repo](https://github.com/Akuukis/deno-pako) where I built pako npm module a bit differently to make it into a Deno module. My reasoning is that I (and perhaps others) could conveniently use it until [official pako](https://github.com/nodeca/pako/) repo will provide the appropriate releases.

After a while I think I made a mistake. Sorry for trouble!

### Problem No.1

Given the situation, I see no way how official pako maintainers would be able to take over the `pako` module name at deno.land once they come around doing so, even if that was my intention to allow them from the beginning.

What's the best way forward? Can it be removed to undo this?

### Problem No.2

I am still puzzled what I had to do instead. How to make my work findable for the community and not block the module name for the original authors at the same time?

**Comment by wperron** [comment]
Hi @Akuukis, if and when the the pako project decides to publish their project on deno.land/x, we can transfer ownership manually. In the meantime we can just leave it as-is. As a rule we don't remove modules that have published versions from the registry.

As for what you _could've_ done; Firstly, it's possible to import ES modules straight from github using their `raw.githubusercontent.com` distribution, that's usually a good idea when trying stuff out. Looking at the pako quickly, I see that it's a package intended to be used in browsers as well, so there's a good chance that it already works out of the box through [skypack](https://www.skypack.dev/view/pako).
