### ISSUE TITLE
chore: bump deno version

### ISSUE THREAD

**Issue by wperron** [denoland/deno_registry2#224]
We're still stuck on 1.6.2 due to us not having checked it for a while and some other reasons (iirc back when we switched to the Docker format for Lambda, there was an issue in `deno bundle` for 1.7 forcing us to stick to 1.6). Those issues have been resolved, and we don't use `deno bundle` anymore in the packaging step so it's about time we upgrade to the latest release of Deno.

PRs welcome obviously, though to properly test it, one needs to deploy the whole thing, so that means signing up to a couple of platforms.

**Comment by wperron** [comment]
Depends on #234

**Comment by crowlKats** [comment]
Closing as deno was upgraded
