### ISSUE TITLE
doc for how to add module ?

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno_registry2#240]
we can add module in easy way, but we can't read about this process in deno.land without doing it

**Comment by wperron** [comment]
The "Publish" button opens up a menu that walks users through how to add a module, including an availability checker for the module name, and will pre-compute the webhook URL -- is there anything missing?

**Comment by elycheikhsmail** [comment]
> The "Publish" button opens up a menu that walks users through how to add a module, including an availability checker for the module name, and will pre-compute the webhook URL -- is there anything missing?

I "publish" test_manager module without pb, but for someboy who want to publish a module for the first need to what are steps befor doing them some kind of tutorial how deploy module on deno.land registry

**Comment by crowlKats** [comment]
Closing as deno.land has instructions on how to publish
