### ISSUE TITLE
Module recovery process is necessary 

### ISSUE THREAD

**Issue by erfanium** [denoland/deno_registry2#241]
denoland modules can't be deleted but GitHub repositories can, so there must be a way to recover a module when its GitHub repo is deleted or not available (e.g. flagged by GitHub).

For example, 12 days ago, two of my repositories was mistakenly flagged by GitHub bots, and my conversations with support didn't work. so I lost two modules on `deno.land` and there is no way to recover them

**Comment by wperron** [comment]
Hey @erfanium, sorry this is happening to you, that sucks. Our recovery process is very much manual at the moment; The scale of the registry means we can comfortably accommodate such support requests. We will most likely look into an automated process when the current process no longer scales.

As for your current predicament, I would happy to help you out, feel free to reach out to me via email (available on my profile) or through Discord and we can work something out from there.

**Comment by wperron** [comment]
Handled offline.
