### ISSUE TITLE
alternative for webhooks

### ISSUE THREAD

**Issue by panva** [denoland/deno_registry2#242]
👋

I have an existing GitHub Actions Workflow that builds, tests, and publishes a module. I've added the dist files to my repo so that they're available in the tagged repo and registered deno.land/x webhook.

That works fine. But if the build would fail for <reason placeholder> I would delete the remote tag, fix the issue and push a new one.

The deno registry would not re-fetch the tag though.

So my question is - is there an alternative way of triggering a publish to deno.land/x that I could use from within my Workflow so that it only happens when CI/CD decides the build is good to go/publish?

**Comment by satyarohith** [comment]
> But if the build would fail for I would delete the remote tag, fix the issue and push a new one.

Does building and testing the code before creating a tag solve the problem?

**Comment by panva** [comment]
d'oh. But it requires me to change my flows, hence me asking for an alternative, something I can trigger on my own terms.

**Comment by wperron** [comment]
At the moment, webhooks are the only publishing mechanism supported for deno.land/x. If you're simply looking to transpile TS -> JS we have an issue opened for that and it will most likely get done in the short to medium term. I would love to be able to support more complex workflows as well, but to be completely, we simply don't have the bandwidth at the moment to make it a priority. I will gladly reopen this issue in the future if and when we're able to tackle it!

In the meantime, there's other options that you can consider; [nest.land](https://nest.land) has a publishing workflow that is closer to the typical npm workflow. you can also publish to NPM directly if you're used to that, and rely on Skypack, esm.sh to import code in Deno/Browsers. You can also string something together yourself with something like an S3 or GCS bucket and a CDN.
