### ISSUE TITLE
New versions with a different naming convention aren't added to deno.land

### ISSUE THREAD

**Issue by dansalias** [denoland/deno_registry2#243]
To better align with the `std` modules I switched from prefixing version tags with `v` to using "pure" semver tags (without the `v` prefix), and rewrote the GitHub tag history. Now publishing a new tag no longer updates the deno.land/x registry.

The repository in question:
- https://github.com/dansalias/aws_s3_presign/releases - latest `1.2.0`
- https://deno.land/x/aws_s3_presign@v1.1.1 - latest `v1.1.1`

**Comment by wperron** [comment]
I'm assuming you still have the `prefix` query string parameter on your webhook?

**Comment by dansalias** [comment]
> I'm assuming you still have the `prefix` query string parameter on your webhook?

In the GitHub webhook settings? I believe not, the URL is `https://api.deno.land/webhook/gh/aws_s3_presign`

**Comment by wperron** [comment]
Can you check your latest webhook execution to see if there are any errors? If there aren't, you should have the response body from the webhook handler with a status URL that you can also check for error messages

**Comment by dansalias** [comment]
Ah, there were no errors, I'm not sure why the most recent tag hadn't propagated but pushing a new tag just now works perfectly. Sorry for the false alarm and thanks for the help!

**Comment by wperron** [comment]
No problem, let us know if there's any other issue :smile:
