### ISSUE TITLE
Missing 3rd party module jsxslack

### ISSUE THREAD

**Issue by slackmon** [denoland/deno_registry2#266]
Can you please help me check why this release https://github.com/slackmon/jsx-slack/releases/tag/v4.3.0 did not properly show up here https://deno.land/x/jsxslack

Webhook seems configured correctly
<img width="955" alt="Screen Shot 2021-10-29 at 10 41 02 AM" src="https://user-images.githubusercontent.com/23177759/139479135-7ecc5f01-86de-46db-9001-fc59c28f94f3.png">

Im totally new to Deno so I may be missing something obvious, thanks

**Comment by kt3k** [comment]
Do you see any items in 'Recent Deliveries' tab? Do those show any errors?

<img width="1205" alt="スクリーンショット 2021-10-31 21 09 50" src="https://user-images.githubusercontent.com/613956/139582505-6ed965fa-b92e-4480-8d8f-7b35d5b36f27.png">

Did you create any tag 'after' setting up the webhook? (The registry only receives the tags after the webhook is set up)

**Comment by crowlKats** [comment]
Closing as stale.
