### ISSUE TITLE
[FEATURE] Add API endpoint to retrieve versions/builds

### ISSUE THREAD

**Issue by secustor** [denoland/deno_registry2#292]
If I'm not mistaken there is no way to retrieve the available version numbers without usage of webhooks. 

For automation purposes we are interested in retrieving the versions of a module.    
This can be achieved by allowing to list builds per module. 

Suggested API endpoint: `GET /modules/:name/builds`

I consider to implement this myself.

**Comment by secustor** [comment]
Thanks for the fast response!    
Is there any issue I can subscribe to or give feedback at?

**Comment by kitsonk** [comment]
Not at the moment, but there will be an announcement when it is made public.

This isn't actionable, so closing.
