### ISSUE TITLE
Possible to move module to a different repo?

### ISSUE THREAD

**Issue by Symbitic** [denoland/deno_registry2#301]
I'm the author of the [webbluetooth](https://deno.land/x/webbluetooth) module.
The current repository is under my account: https://github.com/Symbitic/deno-webbluetooth

However, I am working on a patch for https://github.com/thegecko/webbluetooth to use denoify.
You can see my current work here: https://github.com/Symbitic/webbluetooth/tree/simpleble-port

It isn't ready yet, but will it be possible to move webbluetooth from `Symbitic/deno-webbluetooth` to `thegecko/webbluetooth/deno_dist` when the process is complete?

**Comment by piscisaureus** [comment]
@Symbitic 

To link your deno.land/x module to a different git repo, please contact support at modules@deno.land.
It would also be helpful if you could mention which module on deno.land/x your request applies to.
