### ISSUE TITLE
Query for extra Quota for x/react_icons. + option to disable automatic doc generation for some modules.

### ISSUE THREAD

**Issue by UrielCh** [denoland/deno_registry2#307]
Hi

Weeks ago, I ported [react-icons](https://react-icons.github.io/react-icons/) to deno/X

I shrunk it as much as possible to allow it to fit the 20 MB Quota.

After adding some modules doc, I got completely stuck and had to remove four icons provider to fill the Deno X repo quota.

- Do my port deserve an extra quota to add the four missing providers?
- Can I also have extra space to add js doc in front of each component (should consume five extra MB)

----

Can you add a tag to block automatic doc generation for some modules?

react-icons contain a sub-module for each provider, but the main module lists all the components of each provider, so the page gets too big to be displayed.

```bash
time curl 'https://deno.land/x/react_icons@0.2.3/mod.ts' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9' -H 'Accept-Encoding: gzip, deflate, br' > test.html
```
timeout after 60 seconds.
> curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0

But a sub-module work fine:

```bash
time curl 'https://deno.land/x/react_icons@0.2.3/fa/mod.ts'  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9' -H 'Accept-Encoding: gzip, deflate, br' > fa.html
```
fa.html is less than 80KB

**Comment by crowlKats** [comment]
@UrielCh how much space do you require? for the whole module?

**Comment by UrielCh** [comment]
After a generation of all libs (4 were dropped)
```
du -s --exclude=node_modules --exclude=.git .
21772   .
```

After undoing extra compression minifying:
```
du -s --exclude=node_modules --exclude=.git .
23056   .
```

With a single file per icon:
```
Task size du -s --exclude=node_modules --exclude=.git .
58516   .
```

The last version with a single file per icon, allow access to icons with:
```javascript
import { AiFillAccountBook } from "https://deno.land/x/react_icons@0.2.4/ai/AiFillAccountBook.ts";
```
I think that having a single module per icon, is really too large.

40 Mb will be large enough to fit all icons, and add some more docs.

if you can give me you opinion, I will appreciate.

---
and I still need to find a way to bypass the root doc size issue:

[doc](https://deno.land/x/react_icons@0.2.3?doc)

the root auto-generarted doc with all icons at once is to large to be view in a browser.

**Comment by UrielCh** [comment]
I also start a deno fresh page to test and import icons.

https://react-icons.deno.dev/

I will complete it after my next lib update.

**Comment by UrielCh** [comment]
up

**Comment by UrielCh** [comment]
down I break the project in 30 sub-project.
but now I'm ... ban from deno x ....
