### ISSUE TITLE
Webhooks should also support content-type application/x-www-form-encoded 

### ISSUE THREAD

**Issue by ry** [denoland/deno_registry2#33]
Would just eliminate another gotcha. Should be relatively easy to do.

**Comment by wperron** [comment]
I can take a look at this one if no one is working on it

**Comment by wperron** [comment]
I did some tests using API Gateway and by default it performs a base64 encode when the Content-Type is `application/x-www-form-urlencoded`. The way I see it there's a couple of ways this could be handled:

1.  Check for the `Content-Type` header in the Lambda code, something like a good ol' switch-case would do the trick, quick and dirty, does the job
2. Make a Lambda Layer to handle the Content-Type and perform the base64 decode: makes it more transparent to the webhook code
3. Add a template mapping to the API Endpoint: even more transparent, there wouldn't be any modification to do on the js code, but by experience debugging mapping templates in API Gateway can be a bit of pain, requires pretty in-depth knowledge of API Gateway and the AWS stack. The CloudFormation Template also doesn't include the endpoint at the moment so I don't even how we'd go about deploying this.

What do you guys think?

**Comment by lucacasonato** [comment]
I think the easiest way to get this implemented is option 1, so I would prefer that for now. Later down the line we can investigate implementing option 2 in github.com/hayd/deno-lambda.
