### ISSUE TITLE
latest version has not been released in deno.land/x

### ISSUE THREAD

**Issue by manyuanrong** [denoland/deno_registry2#36]
I have set up a webhook, and confirmed the successful call to deno api through the hook call log, and got the correct response, but the latest version has not been released in `deno.land/x`
![image](https://user-images.githubusercontent.com/7514524/89241522-bcf2ed00-d631-11ea-91e1-8d2b2d635b07.png)
![image](https://user-images.githubusercontent.com/7514524/89241625-10fdd180-d632-11ea-80e8-f44ba803bd7e.png)

**Comment by kidonng** [comment]
Have you cleared your cache? The API has a 4-hour long cache header.
![image](https://user-images.githubusercontent.com/44045911/89247253-8a4ff100-d63f-11ea-8956-232f66f2c0c3.png)

**Comment by manyuanrong** [comment]
The latest version is now available. But before I downloaded the latest version directly by using the url, it also prompted notfound

**Comment by lucacasonato** [comment]
> The latest version is now available. But before I downloaded the latest version directly by using the url, it also prompted notfound

You usually just have to do it a few times before it switches over to the new version. This is because of the cache headers we use.
