### ISSUE TITLE
Support for non-git hosted files?

### ISSUE THREAD

**Issue by balupton** [denoland/deno_registry2#37]
Is there any plans to support packages that are published to npm or [nest](https://nest.land) or their own S3 storage?

As sometimes the result package is the result of compilation, and it isn't nice to have compiled files inside git, as it makes the git changelogs unnecessarily large and makes git diffs filled with junk.

For instance, Bevry maintains about [30 packages](https://www.npmjs.com/search?q=keywords:deno-entry) now that support Deno, Node, and Web Browsers, via [make-deno-edition](https://github.com/bevry/make-deno-edition). This is done by having source code that is compiled to multiple editions that target different environments. Only the source code is committed to git, and not the compiled editions. The compiled code is published via CI to npm, which is then available via many CDNs. This [editions](https://editions.bevry.me) technique allows multiple targets to be supported out of the box, without complicated setups by the consumer, and guaranteed support by the publisher.

A prime example of this is the [caterpillar](https://github.com/bevry/caterpillar) package, which [source code](https://github.com/bevry/caterpillar/tree/master/source) is published to the [multiple editions](https://github.com/bevry/caterpillar#editions), with a [deno example](https://repl.it/@balupton/caterpillar-deno).

**Comment by brandonkal** [comment]
Git is a natural choice for versioning text files. The proposal here would necessitate a CI process at which point you can just as easily publish generated files to a different git repository instead of uploading a tarball to some central registry (which is rather inefficient). Alternatively, you can also already use `.gitattributes` so that your diffs will not include generated files.

As you've already pointed out, nest is an alternative option that already supports your desire for a "zip it into a package and upload it all" approach. There are many other existing solutions as well. I don't see the value added by adding this to `deno.land/x`.

**Comment by jsejcksn** [comment]
> it isn't nice to have compiled files inside git, as it makes the git changelogs unnecessarily large and makes git diffs filled with junk

@balupton I think this is not everyone's opinion, but if it's simply about separation of concerns for your repo, another alternative to [the suggestions provided by](https://github.com/denoland/deno_registry2/issues/37#issuecomment-670816605) @brandonkal is to use a single repository with one branch for source and a different branch for compiled code.

You can use a different `.gitignore` file in each branch, exclusively matching content for that branch.

(e.g. the source branch would ignore non-source (build) files, and the build branch would ignore non-build (source) files)

You might find [negation pattern matching](https://git-scm.com/docs/gitignore#_pattern_format) useful in this case.

**Comment by balupton** [comment]
I understand there are practices that one can adopt to mitigate the extreme performance penalties of staging compiled files.

However, many just publish to a CDN instead. I am working around this with all of Bevry's packages by recommending unpkg for our deno editions. As seen here:

https://github.com/bevry/fellow#deno

It works well enough, and ultimately it seems that trying to have the deno registry supports all the various principles of package production and consumption is futile, and that a userland deno registry that shows the packages from all the variety of different sources (be it deno's official registry, or npm via unpkg, or whatever else) seems to be the way to go to satisfy everyone.
