### ISSUE TITLE
Can you include the owner name or repository name in the GET /modules response?

### ISSUE THREAD

**Issue by yoshixmk** [denoland/deno_registry2#39]
# About GET /modules
https://github.com/denoland/deno_registry2/blob/a6adde77090a64d7cf1bc594493b6ecd34d671b9/API.md#response-1

## Reason
The current response content cannot uniquely identify the repository on Github.

## I'm having trouble
I've created a ranking page based on `database.json` before,  
and I want to switch to the current modules API,  
but cannot know repository details from module contents.

- Products
  - https://yoshixmk.github.io/deno-x-ranking/
- Github
  - https://github.com/yoshixmk/deno-x-ranking/

## Maybe
It may be good to create an API that returns `detailed module info`.

**Comment by divy-work** [comment]
@yoshixmk There was a PR for this. #38 . But they are not keen on adding any new routes. Instead you can use https://cdn.deno.land/MODULENAME/versions/VERSION/meta/meta.json for now.

**Comment by lucacasonato** [comment]
@yoshixmk There has been more demand for an API than expected. I have gotten half a dozen requests about it already. I want to restrain adding all kinds of endpoints for different users, so maybe GraphQL would work nice. Here are some requests  I have gotten so far:

- @divy-work: get a single database entry by name. mostly covered by https://cdn.deno.land/MODULENAME/versions/VERSION/meta/meta.json
- @yoshixmk: get owner and repo name in /modules endpoint
- @MarkTiedemann: an endpoint to get the latest version of a module in plain text
- a few just wanting a version list per module: https://cdn.deno.land/MODULENAME/meta/versions.json

**Comment by yoshixmk** [comment]
Thank you very much. Seems to be able to solve.
