### ISSUE TITLE
Cannot change sub directory

### ISSUE THREAD

**Issue by mesqueeb** [denoland/deno_registry2#41]
Hi,
I uploaded my library [github.com/mesqueeb/is-what](https://github.com/mesqueeb/is-what) to Deno.
But after making a tag I saw this error in the web hook:
```
{"success":false,"info":"provided sub directory is not valid as it does not end with a /"}
```
I remember I wrote `dist` for the location of the distribution folder, and I guess I needed to write `dist/` instead?

How do I change this sub directory now?

When I open my repository on Deno it just says there's no versions:
https://deno.land/x/is_what

Is there any way I can login to the Deno website to edit my repository settings?

**Comment by mesqueeb** [comment]
I fixed it by deleting the `?sub_dir=dist` from the webhook completely.

Feel free to close this.

**Comment by lucacasonato** [comment]
You can just generate a new web hook link on the website at https://deno.land/x#add

**Comment by mesqueeb** [comment]
Yeah i was confused how it all worked in the first place. But understand it now. Thanks!!
