### ISSUE TITLE
kebab-case > camelCase/snake_case

### ISSUE THREAD

**Issue by mesqueeb** [denoland/deno_registry2#46]
I would have hoped Deno would force **kebab case**, because then we could just create the same package names that we use for NPM.

But since that's not the case, (get it? 😛) and DENO seems to force either snake case or camel case, I'm conflicted which to choose.

I've seen both snake and camel case packages, but it seems like there are more snake case packages for Deno over camel case ones.

In a perfect world we would force to use just one case, because than it's consistent and you don't get things like eg. `deno.land/x/caseConverter` and `deno.land/x/case_converter` from 2 different authors and ppl get confused the whole time which they're using.

Any advice on which case we best use?

**Comment by nayeemrmn** [comment]
Between those two, snake case.

I would have also preferred kebab case, since that was the bigger pre-existing convention for repo names, and URL components will never be used as symbols, but 🤷‍♂️.

**Comment by narwy** [comment]
maybe `deno lint` could also convert camel to snake 🤷‍♂️

**Comment by ry** [comment]
I agree that we should avoid similarly named modules. Beyond the problem of case there is also the problem of people intentionally registering slightly misspelled modules.

**Comment by hayd** [comment]
IME kebab-case also had the benefit of google ability, but perhaps it's a bit late to select that? https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

I wonder if there should be some kind of string distance function applied against existing libraries (so you can say "this new module name you're proposing is too close xxx").

**Comment by mesqueeb** [comment]
yeah, if still possible at all, big +1 for kebab case all the way!!

I'd love to make Deno versions of all my node packages and just host them on Deno with the same package name. (therefore, kebab-case.)

**Comment by lucacasonato** [comment]
Our module name filter prevents capital letters and hyphens, so all modules must use snake case. There was a bug, and some modules slipped through, but now you can only use a-z, 0-9, and _.

**Comment by mesqueeb** [comment]
@lucacasonato why not hyphens?

**Comment by lucacasonato** [comment]
The Deno style guide specifies underscores for file names. The logical conclusion from that is that we mandate underscores for modules hosted on deno.land/x.

**Comment by hayd** [comment]
> The Deno style guide specifies underscores for file names.

Yeah, it is the same issue, but that style suggestion is... surprising.
(The same question applies: "why not hyphens?", I suspect the answer is "ry prefers underscores in filenames". 🤷 )

Personally I uses hyphens unless there is a need for separators in the filename then I use underscore too e.g. `topic_file-name_YYYY-MM-DD.csv` e.g. perhaps in lieu of directory structure (`topic/YYYY-MM-DD/file-name.csv`) or otherwise.

**Comment by nayeemrmn** [comment]
Yep, in my comment above complaining about snake case I was referring to the original file name convention in the style guide.

Hey, `std` is unstable and everything else is internal so it's technically not too late to change, right?? 🤪

**Comment by mesqueeb** [comment]
@lucacasonato can we deprecate the suggestion in the style guide of `snake_case` for `kebab-case` ?

**Comment by lucacasonato** [comment]
We are keeping casing as is.

**Comment by niedzielski** [comment]
Sorry to comment on an old issue but I think this decision should be reconsidered given that NPM imports are now supported.

In my view, standard Deno packages can continue to use underscores. However, allowing user packages to include hyphens will give authors flexibility to preserve the consistency of their existing Git repo names, many of which use NPM-supported naming conventions like kebab-case.
