### ISSUE TITLE
Can one add JavaScript project to Third Party Modules?

### ISSUE THREAD

**Issue by mk0y** [denoland/deno_registry2#47]
What are requirements here? Is mod.ts mandatory?

I'm trying to add a module with only JavaScript files. So far I'm importing it through Github raw file url, which works.

All I'm getting is:
```
No uploaded versions

This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed.
```

I have created webhook and first tags/releases after creating space on deno.land/x.

Does it have to be TypeScript? I'm waiting for TypeScript version 4.0 to be ready in order to update the project to TS.

**Comment by lucacasonato** [comment]
@mk0y Yes you can add pure JS modules. What module are you taking about? Sometimes you just need to refresh the page a few times before the module shows up (Ctrl-Shift-R).

If this does not help: Can you verify that the GitHub webhooks arrived? You can see this in the GitHub webhook settings. Can you also check that you have the `create` event selected for your webhook? If not, please enable it and recreate the tag.

**Comment by mk0y** [comment]
@lucacasonato it works after Ctrl-Shift-R. :) Thanks!

**Comment by mk0y** [comment]
It was about https://github.com/Vertrical/tino.
