### ISSUE TITLE
Module Search Does Not Reflect Value

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno_registry2#56]
I believe the search functionality could be improved somewhat, to give results more specific to the value type in the input field.

For example, take this. scenario I did minutes ago:

1. Go to https://deno.land/x/
2. Type "ssh" into the search bar
3. Results seen doesn't seem to match anything related to ssh (I was hoping someone made a ssh client).

What I would expect to see are modules related to ssh, or if none exist (which i don't think there are), no modules should display

**Comment by t8** [comment]
Perhaps they could consider implementing an Algolia search into registry2 instead? They give free API keys to open source projects.

**Comment by ebebbington** [comment]
Based on the results after keystrokes, it seems the dynamic updating (i assume it's using a react component to hold module info) is already pretty fast - though I had to google what Algolia was!

**Comment by t8** [comment]
For sure. It is pretty speedy, but I think something like Algolia could accomplish the same task. 

See [FontAwesome's Icon Gallery](https://fontawesome.com/icons?d=gallery) for an example of Algolia searching. It is **really** powerful.

**Comment by lucacasonato** [comment]
Yeah I originally wanted to use Algolia, but ultimately we decided on MongoDB Atlas full text fuzzy search because it was simpler to integrate. I kinda wanna move to Algolia now because of the horrendous results we are getting from MongoDB Atlas. I'll add it to the roadmap

**Comment by lucacasonato** [comment]
I am going to close this in favor of #69.
