### ISSUE TITLE
Configure a dead letter queue for the builds queue

### ISSUE THREAD

**Issue by wperron** [denoland/deno_registry2#60]
Configure a second SQS queue to act as a dead letter queue for bad builds. This would avoid a situation where failing events start piling up in the main queue forever and drive the cost of lambda executions up for no reason. There's an [example available in the official docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-properties-sqs-queues--examples--Amazon_SQS_Queue_with_a_Dead-Letter_Queue--yaml).

There shouldn't be anything else to modify other than the `template.yaml`, SQS manages the dispatch of messages to the DLQ on its own.

As far as cost is concerned, in a best case scenario where no builds are ever failing or timing out there won't be any difference on the end-of-month bill since SQS only charges by the amount of PUT requests on the queue. In a worst case scenario where a significant number of builds are failing this will actually lower the end-of-month bill because it will avoid reprocessing those events, and thus reduce the Lambda execution costs.

**Comment by lucacasonato** [comment]
So far we have had no failed builds 🤞 but preventing it from getting out of control in the future seems like a good plan. 👍

**Comment by wperron** [comment]
great, I'll start working on it
