### ISSUE TITLE
The total count is different from the total count of hits.

### ISSUE THREAD

**Issue by yoshixmk** [denoland/deno_registry2#64]
About ` GET /modules`, total_count is defferent from all results length(※ It only returns 100 at a time, so combine the results).  
```ts
Deno.test("fetchAll hit count sum EQ fetchOne total count", async () => {
  const module = await fetchOne(); // Expect total_count
  const modules = await fetchAll();  // Actual flatMapped array, every per 100
  assert(modules.every((m) => m.success === true)); // Pass

  const sum = modules.map((m) => m.data.results.length)
    .reduce(
      (accumulator, currentValue) => accumulator + currentValue,
      0,
    );
  assertEquals(sum, module.data.total_count); // Fail
});
```
test result:  
```
[Diff] Actual / Expected
-   919
+   925
```

`fetchAll` and `fetchOnesource` function detail code:  
https://github.com/yoshixmk/deno-x-ranking/blob/master/src/repositories/registry_repository.ts#L19-L44

**Comment by wperron** [comment]
pretty sure the total count takes into unlisted modules, but the results only show visible modules

**Comment by lucacasonato** [comment]
I knew this was the case but I didn't think it was gonna be an issue. I agree the total shouldn't include the unlisted modules.

**Comment by yoshixmk** [comment]
Thanks a lot.
