### ISSUE TITLE
scoped urls

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_registry2#67]
Just wondering if it would make sense to have modules scoped to avoid name clashes?

```https://deno.land/x/USER/IDENTIFIER@VERSION/FILE_PATH```
instead of
```https://deno.land/x/IDENTIFIER@VERSION/FILE_PATH```

**Comment by wperron** [comment]
I have no strong feelings about this feature, but it's worth noting that the sites that do offer this feature (eg: npm, docker hub) also have some form of login, which we don't have right now, that would need to be done first.

**Comment by timreichen** [comment]
I agree that it should not require any login.
I thought since it uses github reps, we could add the username automatically to the chosen module name without any form of login.

**Comment by ry** [comment]
I like flat namespaces. Other registries can do that if they want.
