### ISSUE TITLE
Module not published - Failed to run dependency analysis.

### ISSUE THREAD

**Issue by quaos** [denoland/deno_registry2#68]
Dear Denoland team,

I've just created a module name here:
https://deno.land/x/deno_react_minimal_frontend

And setup a webhook on my repository.
However, after first release for some hours, the module is not showing up.
The latest publish status page, by the following link, showed message: "Published module. Failed to run dependency analysis."
https://deno.land/status/5f3a03db00d00ffe00127d06

Please help check what should I do next.
Best Regards,
Chakrit W.

**Comment by lucacasonato** [comment]
Even if the dependency analysis fails, the module should still be published. I can see the 1.0.0 uploaded: https://deno.land/x/deno_react_minimal_frontend@v1.0.0. This might be a caching issue. Try reload with a cleared cache (`Ctrl-Shift-R` in Chrome).

**Comment by quaos** [comment]
@lucacasonato Oh, I see it came up now. Thanks!
