### ISSUE TITLE
Improve module search

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_registry2#69]
Successor to #56

## Problem

1. The search results are not biased by star count. Some examples:
   - term: _discord_: the highest star count module is only on place 6.
2. There are no filtering or alternative sorting capabilities (last uploaded at, supports typescript, no external imports)
3. Search is not always very relevant to what was searched.
4. No filtering by module tags

## Solution

1. We need to include more data in the documents being searched (github tags, last upload date, and other stats/metrics).
2. Use a better search engine. I would like to use MeiliSearch because of the search customizability and API (cc @erlend-sh). We need to find a way to host it / get access to a hosted instance. This would also involve pushing updates to the documents in the database to the search engine. This can be accomplished relatively easily.

**Comment by wperron** [comment]
Just looked at MeiliSearch's repo, they have an official docker image, I'm thinking we could set it up on Fargate relatively easily

**Comment by cknight** [comment]
Could the project root README feed into the search engine? This would hopefully give a more relevant set of data to work with than just the module name and tag line (unless there is more?).

**Comment by itohatweb** [comment]
This issue is being open for over a year now. Will this be fixed, or is this not a high priority?

**Comment by lts20050703** [comment]
### Search is extremely broken, <https://deno.land/x?query=oak> does not even show up <https://deno.land/x/oak>, please fix asap this annoys me a lot.
![image](https://user-images.githubusercontent.com/87189679/152381368-67226b85-4e3f-46ac-b3d9-438903a19f32.png)

**Comment by crowlKats** [comment]
Search has been fixed on dotland, so will close
