### ISSUE TITLE
About the ranking system

### ISSUE THREAD

**Issue by garronej** [denoland/deno_registry2#77]
![image](https://user-images.githubusercontent.com/6702424/90589807-48967d00-e1df-11ea-8f9d-74a6e2c452aa.png)

The first 8 third party repo do not provide type definitions, are not indexed by a `mod.ts` files, most do not have Deno specific instructions, some have no `README.md` at all.

It must be a put-off for people wanting to use the third party module repository. 
Besides those modules still the spot of legit Deno modules.

Maybe the star-based ranking system should feature a system of penalty for module that are not "Denoish" enough.

Regards

**Comment by lucacasonato** [comment]
This is a good point, and something we are working towards. On the roadmap (#35) you can see that we are planning to analyze modules when they are published. This data will be used to rank modules and give them scores.
