### ISSUE TITLE
Support for adding modules from specific GitHub branches?

### ISSUE THREAD

**Issue by nebrelbug** [denoland/deno_registry2#78]
I'd like to convert some of my npm packages so they're Deno-compatible and publish them on https://deno.land/x. The way I'd like to do that is by creating a `deno` branch for the Deno version of the package -- that would hopefully allow me to keep both the Node and Deno versions in sync.

Is there a way to add a specific branch of a GitHub repository to the registry?

**Comment by ebebbington** [comment]
No, you can only target release tags

**Comment by nebrelbug** [comment]
@ebebbington okay, that makes sense. I think what I'll end up doing is creating an organization called "Denoized" and forking my projects to it so I can keep them synced.

Does that sound like a good idea? It looks like you have some experience creating Deno modules; I'd love it if you had any advice. Thanks!

**Comment by lucacasonato** [comment]
Can't you make a deno subdirectory in your project?

**Comment by jeroenptrs** [comment]
@nebrelbug you should use https://github.com/garronej/denoify

**Comment by nebrelbug** [comment]
@lucacasonato I could (and perhaps should), but I'm worried that might make it harder to keep the Deno and main versions in sync.

I also need to worry about writing tests for the Deno version. Some polyfills in the main version are unnecessary, so I'll be able to remove some tests. I also plan on slightly tweaking some APIs for the Deno version (replacing callbacks with Promises, etc.)

**Comment by nebrelbug** [comment]
@jeroenptrs hmm, maybe I should use Denoify. I didn't realize it allowed you to override modules by file (which would make keeping a Deno version synced a lot easier).

As far as testing goes, I could create two new folders beside `/tests`: `deno_tests` and `main_tests`. I could run `/tests` on the Deno and main distributions, and then run only `deno_tests` for the Deno distribution and `main_tests` for the main distribution.

**Comment by ebebbington** [comment]
@lucacasonato i didn't think about that... though i feel it might get messy... with a mod.ts on top of the node ecosystem, as well as the releases either incl the Deno release or starting to make releases just for Deno - tbh i just ended up making a new repo for a deno port (i **wanted** to write it using deno) as the package was already finished, it. was just a fairly basic copy and paste job, but having a `deno` dir could work well, might give it a try myself.

@nebrelbug i'm not too familiar of this area of deno unfortunately

**Comment by lucacasonato** [comment]
Nothing actionable here, so closing.
