### ISSUE TITLE
registering new third party modul seems to have hiccups  - see screenshot

### ISSUE THREAD

**Issue by michael-spengler** [denoland/deno_registry2#83]
![Screen Shot 2020-08-21 at 9 35 56 PM](https://user-images.githubusercontent.com/43786652/90928149-9fc26a80-e3f6-11ea-86c5-9a89d98dc2ee.png)

... came when saving the webhook for new third party module named telegram_bot_ui

**Comment by michael-spengler** [comment]
potentially detected new hiccups :) 

![Screen Shot 2020-08-29 at 4 36 53 PM](https://user-images.githubusercontent.com/43786652/91639319-fdb60a00-ea15-11ea-9f9b-9048be86a0e9.png)

**Comment by lucacasonato** [comment]
@michael-spengler What is the response?
