### ISSUE TITLE
Limit for modules registered by one user

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_registry2#85]
There should be a default limit of 5 modules registered per user or GitHub org. Limit increases can be requested from me. The list of user accounts with limits should be stored in the database.

**Comment by caspervonb** [comment]
> or GitHub org

Hmm, it's fairly hassle free to register orgs tho 🤔

**Comment by lucacasonato** [comment]
> Hmm, it's fairly hassle free to register orgs tho thinking

Sure, but putting more stones in the way of people that want to squat names might make them reconsider.
