### ISSUE TITLE
Hiccups during webhook creation

### ISSUE THREAD

**Issue by michael-spengler** [denoland/deno_registry2#89]
![Screen Shot 2020-08-29 at 4 36 53 PM](https://user-images.githubusercontent.com/43786652/91639346-348c2000-ea16-11ea-896c-e3a31779f9ac.png)

**Comment by lucacasonato** [comment]
@michael-spengler What is the response?

**Comment by wperron** [comment]
the name `web` is already taken : https://deno.land/x/web@0.2.1

**Comment by michael-spengler** [comment]
@lucacasonato sorry hiccup on my side :) 

![Screen Shot 2020-08-29 at 5 18 01 PM](https://user-images.githubusercontent.com/43786652/91640133-a155e900-ea1b-11ea-8694-69a266751e31.png)

**Comment by michael-spengler** [comment]
my modules are rather fine granular - therefore it seems I reached a limit - probably it is time to relax :)

**Comment by michael-spengler** [comment]
I just followed the instructions in the body :) --> closing this issue - sorry - no hiccup on registry side :) 

Hi Ryan. 

I guess it makes sense to have such a limit to avoid spam :) 

What can I do to qualify to publish more deno modules. I like that shit :) 

My org is: https://github.com/michael-spengler

Kind regards 
Michael
